name: Go

on:
  push:
  workflow_dispatch:

jobs:
  test:
    name: "test (age ${{ matrix.age_version }}, restic ${{ matrix.restic_version }})"
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          # nixos-25.05
          - age_version: "1.2.1"
            restic_version: "0.18.0"

          # nixos-25.11
          - age_version: "1.2.1"
            restic_version: "0.18.1"

          # nixpkgs-unstable
          - age_version: "1.3.1"
            restic_version: "0.18.1"

          # matches the restic-api version vendored in go.mod
          - age_version: "1.3.1"
            restic_version: "0.19.1"

    env:
      AGE_VERSION: "${{ matrix.age_version }}"
      RESTIC_VERSION: "${{ matrix.restic_version }}"

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - uses: jdx/mise-action@v4
        with:
          install: true
          cache: true
      - name: Install age
        run: |
          set -o xtrace
          curl --location https://github.com/FiloSottile/age/releases/download/v${AGE_VERSION}/age-v${AGE_VERSION}-linux-amd64.tar.gz --output age.tar.gz
          tar -xzf age.tar.gz
          chmod +x age/age
          sudo mv age/age /usr/local/bin/age

      - name: Install restic
        run: |
          set -o xtrace
          curl --location https://github.com/restic/restic/releases/download/v${RESTIC_VERSION}/restic_${RESTIC_VERSION}_linux_amd64.bz2 --output restic_${RESTIC_VERSION}_linux_amd64.bz2
          bunzip2 restic_${RESTIC_VERSION}_linux_amd64.bz2
          chmod +x restic_${RESTIC_VERSION}_linux_amd64
          sudo mv restic_${RESTIC_VERSION}_linux_amd64 /usr/local/bin/restic

      - name: Build
        run: |
          go build ./...

      - name: Test
        run: |
          go test ./...
